# -*- coding: utf-8 -*-
"""mlbasictask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17gxWPIrWkyGgSAuzKvGxBMpNq7wViNNV
"""

from google.colab import drive
drive.mount('/content/drive')

##installing all the required libraries and modules
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader, random_split
import matplotlib.pyplot as plt
import numpy as np
import os
import zipfile
from PIL import Image

#unzipping the file and storing the path to the folder
zip = "/content/drive/MyDrive/archive.zip"
extract = "/content/vehicle_dataset"

with zipfile.ZipFile(zip, 'r') as zip_ref:
    zip_ref.extractall(extract)

##defining the transforms to resize the images and convert it to tensors
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()])



#storing the dataset
dataset =datasets.ImageFolder(root="/content/vehicle_dataset/Vehicles", transform=transform)

#splitting the dataset into training and testing data
train_size =int(0.8 * len(dataset))
test_size =len(dataset)-train_size
train_data,test_data = random_split(dataset,[train_size,test_size])

#loading the data
train_loader =DataLoader(train_data, batch_size=32, shuffle=True)
test_loader =DataLoader(test_data, batch_size=32, shuffle=False)

#gpu command
device = torch.device("cuda" if torch.cuda.is_available() else "gpu")


#using the pretrained model resnet18
model = models.resnet18(pretrained=True)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 7)  # 7 classes

#sending the model to gpu
model = model.to(device)

#defining the loss and optimizer functions
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


##training the model

epochs = 3
for epoch in range(epochs):
    model.train()
    training_loss = 0
    correct = 0
    total = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device) ##sending the image and label to the gpu
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        training_loss += loss.item()
        predicted = outputs.max(1)[1]
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()
    training_acc = correct*100/total

    print(f"Epoch {epoch+1}/{epochs}, Loss: {training_loss:.4f}, Accuracy: {training_acc:.2f}%")
    print()

##testing the model
model.eval()
test_loss = 0
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        loss = criterion(outputs, labels)

        test_loss += loss.item()
        predicted = outputs.max(1)[1]
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()
    test_acc = correct*100/total

print(f"Validation Loss: {test_loss:.4f}, Accuracy: {test_acc:.2f}%")
print()

#printing predictions
import random

class_names = dataset.classes  #List of class names
print()
print("Sample predictions:")

shown_classes = set()
for img1, label in dataset.samples:
    if dataset.classes[label] in shown_classes:
        continue
    image = Image.open(img1)
    img_tensor = transform(image).unsqueeze(0).to(device) ##add a dimension to match 4D tensor
    with torch.no_grad():
      output = model(img_tensor)
      predicted = output.max(1)[1]
    img_tensor = img_tensor.squeeze()
    img = img_tensor.cpu().numpy().transpose((1, 2, 0)) ##to change the height, width, colour channels order in tensors
    plt.imshow(img)
    plt.title(f"Actual: {dataset.classes[label]}, Predicted: {dataset.classes[predicted.item()]}")
    plt.axis('off')
    plt.show()
    shown_classes.add(dataset.classes[label])
    if len(shown_classes) == 7:
        break